os: linux
language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  global:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.3"
    - LUAJIT="luajit 2.0"
    - LUAJIT="luajit 2.1"
branches:
  only:
    - master
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA --cflags=$LUA_CFLAGS
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install busted
install:
  - luarocks install --only-deps rockspec/euluna-dev-0.rockspec
script:
  - busted -c
  - luacheck euluna-compiler
after_success:
  - luacov-coveralls -v