os: linux
language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0
env:
  matrix:
    #- LUA="lua 5.1"
    - LUA="lua 5.3"
    #- LUA="luajit 2.0"
    - LUA="luajit 2.1"
branches:
  only:
    - master
before_install:
  - unset CXX
  - unset CC
  - mkdir -p latest-gcc-symlinks
  - ln -s /usr/bin/gcc-7 latest-gcc-symlinks/gcc
  - ln -s /usr/bin/g++-7 latest-gcc-symlinks/g++
  - ln -s /usr/bin/clang-5.0 latest-gcc-symlinks/clang
  - ln -s /usr/bin/clang++-5.0 latest-gcc-symlinks/clang++
  - export PATH=$PWD/latest-gcc-symlinks:$PATH
  - sudo pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install cluacov
  - luarocks install luacov-coveralls
  - luarocks install busted
install:
  - luarocks install --only-deps rockspec/euluna-dev-0.rockspec
script:
  - busted -c -r complete
  - luacheck euluna-compiler
after_success:
  - luacov-coveralls -v